import Head from "next/head"
import React from 'react'


export const defaultTitle = "MyApp website"


export default function Layout({
    children, home, title
}: {
    children: React.ReactNode
    home?: boolean
    title?: string
}) {
    return (
        <>
            <Head>
                <title>{title ? title : defaultTitle}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                {children}
            </main>
        </>
    )
}